"""add_visit_indexes

Revision ID: 834a22f77aa9
Revises: 6c91540924cb
Create Date: 2026-09-29 12:26:56.836482

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '834a22f77aa9'
down_revision: Union[str, None] = '6c91540924cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_visits_doctor_id'), 'visits', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_visits_patient_id'), 'visits', ['patient_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_visits_patient_id'), table_name='visits')
    op.drop_index(op.f('ix_visits_doctor_id'), table_name='visits')
    # ### end Alembic commands ###
