"""add_soap_label_confidence_to_chat_messages

Revision ID: f5f4470169cb
Revises: c3e7a9b1d5f4
Create Date: 2026-10-05 15:56:40.409267

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5f4470169cb'
down_revision: Union[str, None] = 'c3e7a9b1d5f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_messages', sa.Column('soap_label', sa.String(), nullable=True))
    op.add_column('chat_messages', sa.Column('soap_confidence', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_messages', 'soap_confidence')
    op.drop_column('chat_messages', 'soap_label')
    # ### end Alembic commands ###
